### ISSUE TITLE
Session data missing

### ISSUE THREAD

**Issue by drzax** [propublica/qis#4]
Something seems to be destroying session data between requests.

If I add a `puts session[:access_token]` right before the end of `get '/' do` it echos what you'd expect, but by the time it gets to the start of the `post '/result' do` handler `puts session[:access_token]` is empty.

It looks to be something to do with session cookies and the `localhost` domain: http://stackoverflow.com/questions/1134290/cookies-on-localhost-with-explicit-domain

**Comment by ashaw** [comment]
I haven't been able to reproduce this bug. I just bumped some of the dependencies.. Can you do a bundle update and see if it's still happening.

Also, does your keys.yml look like this?

    root_uri: http://localhost:4567/
    instagram_client_id: YOURKEY
    instagram_secret: YOURKEY

**Comment by drzax** [comment]
I can't reproduce this using a fresh checkout at home. Will check again at work tomorrow where I first encountered the issue.
